# Generated by Django 3.2.7 on 2024-05-11 19:14

import channel.models
import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_art', models.ImageField(blank=True, default='channel-art.jpg', null=True, upload_to=core.models.user_directory_path)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.user_directory_path)),
                ('full_name', models.CharField(max_length=200)),
                ('channel_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disable', 'Disable')], default='active', max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('total_views', models.IntegerField(default=0)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('make_business_email_public', models.BooleanField(default=False)),
                ('business_location', models.CharField(blank=True, max_length=500, null=True)),
                ('make_business_location_public', models.BooleanField(default=False)),
                ('website', models.URLField(default='https://my-website.com/')),
                ('instagram', models.URLField(default='https://isntagram.com/')),
                ('facebook', models.URLField(default='https://facebook.com/')),
                ('twitter', models.URLField(default='https://twitter.com/')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=channel.models.user_directory_path)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disable', 'Disable')], default='active', max_length=100)),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Community Posts',
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='channel.community')),
            ],
            options={
                'verbose_name': 'Community Comments',
                'verbose_name_plural': 'Community Comments',
            },
        ),
    ]
